networks:
  default: mainnet-fork

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - 16slim/v3-core@1.0.2-solc-0.8-simulate

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
      - "@uniswap=16slim/v3-core@1.0.2-solc-0.8-simulate"

    optimizer:
      details:
          yul: true
