networks:
  default: mainnet-fork

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
    viaIR: true
    optimizer:
      details:
          yul: true
